[package]
name = "aoc"
version = "0.1.0"
authors = ["joe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.0"
proc = { path = "proc/" }
nom = {version = "6.0.1", features = ["alloc"]}
structopt = "0.3"
